1. Import Dependencies:

In [179]:
import numpy as np
import pandas as pd
import difflib 
from sklearn.feature_extraction.text import TfidfVectorizer  # Correction ici
from sklearn.metrics.pairwise import cosine_similarity

2. Data collection & preprocessing:

A- Dowlanding the data:

In [180]:
data = pd.read_csv("C:\Machine_learning Python\projets\AtelierRecomendation\data.csv")

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\HP\AppData\Local\Temp\ipykernel_58408\3765991129.py:1: SyntaxWarning: invalid escape sequence '\M'
  data = pd.read_csv("C:\Machine_learning Python\projets\AtelierRecomendation\data.csv")


B- Head of the data :

In [181]:
# Renaming the column
data.rename(columns={'Atelier Recomender': 'Atelier_Recomender'}, inplace=True)

# Verify the change
print(data.columns)


Index(['Age', 'Main Domain', 'Main Domain Percentage', 'Favorite Subject',
       'Area of Interest', 'Atelier_Recomender'],
      dtype='object')


In [182]:
data.head()

Age Main Domain  Main Domain Percentage                   Favorite Subject  \
0   12     Biology                    87.0                            Biology   
1    9     O Level                    80.0  Finance / Accounting / Statistics   
2   16     Biology                    87.0                            Physics   
3   13    Computer                    75.0                   Computer Science   
4   10    Computer                    83.0                   Computer Science   

          Area of Interest       Atelier_Recomender  
0             Bio Sciences             Bio Sciences  
1  Business Administration  Business Administration  
2             Bio Sciences             Bio Sciences  
3     Software Engineering         Computer Science  
4     Software Engineering     Software Engineering

In [183]:
data = data.drop(columns=["Main Domain Percentage"], axis=1)

C- Number of tow and columns:

In [184]:
data.shape

(1017, 5)

D- Type of the columns data :

In [185]:
data.dtypes

Age                    int64
Main Domain           object
Favorite Subject      object
Area of Interest      object
Atelier_Recomender    object
dtype: object

E- Information about the data:

In [186]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017 entries, 0 to 1016
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Age                 1017 non-null   int64 
 1   Main Domain         1017 non-null   object
 2   Favorite Subject    1017 non-null   object
 3   Area of Interest    1017 non-null   object
 4   Atelier_Recomender  1017 non-null   object
dtypes: int64(1), object(4)
memory usage: 39.9+ KB


In [187]:
data.head()

Age Main Domain                   Favorite Subject  \
0   12     Biology                            Biology   
1    9     O Level  Finance / Accounting / Statistics   
2   16     Biology                            Physics   
3   13    Computer                   Computer Science   
4   10    Computer                   Computer Science   

          Area of Interest       Atelier_Recomender  
0             Bio Sciences             Bio Sciences  
1  Business Administration  Business Administration  
2             Bio Sciences             Bio Sciences  
3     Software Engineering         Computer Science  
4     Software Engineering     Software Engineering

In [188]:
data["Main Domain"].value_counts()

Main Domain
Computer    532
Biology     326
O Level     104
Arts         55
Name: count, dtype: int64

In [189]:
data = data.drop(data[data['Main Domain'] == 'O Level'].index)

In [190]:
data.head()

Age Main Domain                   Favorite Subject      Area of Interest  \
0   12     Biology                            Biology          Bio Sciences   
2   16     Biology                            Physics          Bio Sciences   
3   13    Computer                   Computer Science  Software Engineering   
4   10    Computer                   Computer Science  Software Engineering   
6   15    Computer  Finance / Accounting / Statistics   Account and Finance   

        Atelier_Recomender  
0             Bio Sciences  
2             Bio Sciences  
3         Computer Science  
4     Software Engineering  
6  Business Administration

F- Selection the releveant features:

In [191]:
selected_features = ["Main Domain","Favorite Subject", "Area of Interest"]
print(selected_features)

['Main Domain', 'Favorite Subject', 'Area of Interest']


2. General statistical :

A- Replacing the null values (just for 5 columns ):

In [192]:
for feature in selected_features:
    data[feature] = data[feature].fillna(' ')

B- Combining all the selectef_features:

In [193]:
combined_feature = data["Main Domain"] + ' '+data["Favorite Subject"] + ' '+data["Area of Interest"]+' '

In [194]:
print(combined_feature)

0                           Biology Biology Bio Sciences 
2                           Biology Physics Bio Sciences 
3         Computer Computer Science Software Engineering 
4         Computer Computer Science Software Engineering 
6       Computer Finance / Accounting / Statistics Acc...
                              ...                        
1011    Biology Finance / Accounting / Statistics Busi...
1012                Biology English Software Engineering 
1014                Biology English Software Engineering 
1015                Biology English Software Engineering 
1016                Biology English Software Engineering 
Length: 913, dtype: object


C- Converting the text data to feature vector:

In [195]:
vectorizer = TfidfVectorizer()

In [196]:
feature_vector = vectorizer.fit_transform(combined_feature)

In [197]:
print(feature_vector)

  (0, 20)	0.4962559352788647
  (0, 5)	0.4962559352788647
  (0, 6)	0.7123623329465129
  (1, 17)	0.6681263718600605
  (1, 20)	0.4691581130955203
  (1, 5)	0.4691581130955203
  (1, 6)	0.33673206122734173
  (2, 12)	0.4654312249485887
  (2, 21)	0.6038114142937557
  (2, 19)	0.4090824205352697
  (2, 10)	0.5014350646100004
  (3, 12)	0.4654312249485887
  (3, 21)	0.6038114142937557
  (3, 19)	0.4090824205352697
  (3, 10)	0.5014350646100004
  (4, 3)	0.3595031987921331
  (4, 0)	0.3595031987921331
  (4, 22)	0.3476308450786321
  (4, 1)	0.3476308450786321
  (4, 14)	0.6744774073603266
  (4, 10)	0.21189789564026415
  (5, 15)	0.5708150679409961
  (5, 22)	0.45112476855930383
  (5, 1)	0.45112476855930383
  (5, 14)	0.4376387604861152
  :	:
  (907, 12)	0.47299769219627835
  (907, 21)	0.6136275139560411
  (907, 6)	0.3463996656744084
  (908, 2)	0.5641776157810681
  (908, 7)	0.5641776157810681
  (908, 22)	0.3164988504702065
  (908, 1)	0.3164988504702065
  (908, 14)	0.3070373747320704
  (908, 6)	0.262282751096775

3. Cosing Similarity:

A- Similarity scores:

In [198]:
similarity_list = cosine_similarity(feature_vector)

In [199]:
print(similarity_list)

[[1.         0.70552023 0.         ... 0.24676207 0.24676207 0.24676207]
 [0.70552023 1.         0.         ... 0.11664387 0.11664387 0.11664387]
 [0.         0.         1.         ... 0.59066319 0.59066319 0.59066319]
 ...
 [0.24676207 0.11664387 0.59066319 ... 1.         1.         1.        ]
 [0.24676207 0.11664387 0.59066319 ... 1.         1.         1.        ]
 [0.24676207 0.11664387 0.59066319 ... 1.         1.         1.        ]]


In [200]:
print(similarity_list.shape)

(913, 913)


B- Getting the movie name:

In [201]:
atelier_name = input("Enter your favourite atelier name: ")

C- Creating a list of all the movies names given the dataset:

In [202]:
Atlier_list = data["Atelier_Recomender"].to_list()

D- Finding the close match for the movie name giving by the user:

In [203]:
finding = difflib.get_close_matches(atelier_name, Atlier_list)
print(finding)

[]


In [204]:
close_match = finding[0]
print(close_match) #Most similar movie

IndexError: list index out of range

E- Finding the index of the movie with title:

In [ ]:

index = data[data['Atelier_Recomender'] == close_match].index.values[0]
print(index)

0


F- Find the similar movie:

In [ ]:
similarity_score = list(enumerate(similarity_list[index]))

E- Sorting the movie based on hteir similarity score:

In [ ]:
sorted_list = sorted(similarity_score , key= lambda x:x[1] , reverse=True)

F- The most similar movie (suggestion):

In [ ]:
i = 1
print("The top 10 similar movies to '", atelier_name, "' are: \n")
for index_score in sorted_list[1:11]:  # Assuming sorted_list contains tuples of (index, similarity score)
    movie_index = index_score[0]  # Extract the movie index from the tuple
    title = data.iloc[movie_index]['Atelier_Recomender']  # Use iloc to access the DataFrame row by integer location
    print("TOP", i, ":", title)
    i += 1

The top 10 similar movies to ' science ' are: 

TOP 1 : Bio Sciences
TOP 2 : Bio Sciences
TOP 3 : Bio Sciences
TOP 4 : Bio Sciences
TOP 5 : Bio Sciences
TOP 6 : Psychology
TOP 7 : Bio Sciences
TOP 8 : Bio Sciences
TOP 9 : Bio Sciences
TOP 10 : Bio Sciences
